In [ ]:
import time
import numpy as np

x=np.random.rand(10000000)
print(len(x))
print(x)

strt=time.time()
Nrmlmean=sum(x)/len(x)
print(time.time()-strt)

strt1=time.time()
Npmean=np.mean(x)
print(time.time()-strt1)

print(Nrmlmean)
print(Npmean)

In [ ]:
A=[2,3,4,5.0,'s',[7,8,9,7]]
print(A)
print(type(A))

A=np.array([[2,3,4],[7,8,9]])
print(A)
print(type(A))

A=np.array([2,3,4])
print(A)
print(type(A))

[2, 3, 4, 5.0, 's', [7, 8, 9, 7]]
<class 'list'>
[[2 3 4]
 [7 8 9]]
<class 'numpy.ndarray'>
[2 3 4]
<class 'numpy.ndarray'>


In [ ]:
print(A[0])

2


In [ ]:
A=np.array([4,5,1,2,5,7,8,5])
for i in range(len(A)):
  if i%2==0:
    print(A[i])


In [ ]:
print(A.shape)
A1=np.array([[2,3,4],[7,8,9]])
print(A1.shape)
print(type(A1))
print(A1.dtype)

(8,)
(2, 3)
<class 'numpy.ndarray'>
int64


In [ ]:
A1=np.array([[2,3,4,7,7],[7,8,9]])
print(A1)
print(A1[0])

[list([2, 3, 4, 7, 7]) list([7, 8, 9])]
[2, 3, 4, 7, 7]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [ ]:
A1=np.array([[2,3,4,7],[1,2,7,8],[4,5,7,1],[0,1,2,3]])
print(A1)
#print(A1[0,1])

for i in range(len(A1)):
  for j in range(len(A1)):
    if i==j:
      print(A1[i,j])


[[2 3 4 7]
 [1 2 7 8]
 [4 5 7 1]
 [0 1 2 3]]
2
2
7
3


In [ ]:
for i in range(len(A1)):
  for j in range(len(A1)):
    if i+j==len(A1)-1:
      print(A1[i,j])

In [ ]:
A1=np.array(1)
A2=np.array([1,2,4,5])
A3=np.array([[1,2,4,5],[2,3,4,5]])
A4=np.array([[[1,2,4,5],[2,3,4,5]],[[1,2,4,5],[2,3,4,5]]])
print(len(A1.shape))
print(len(A2.shape))
print(len(A3.shape))
print(len(A4.shape))
print(A4.ndim)


0
1
2
3
3


In [ ]:
A=[1,4,5,7]
B=(1,2,4,5)
D={3,4,5,6}
C='123'
Out=np.array(A,ndmin=3)
print(Out)
print(Out.ndim)

[[[1 4 5 7]]]
3


In [ ]:
A=[1,2,1.2,2.2,'2']
Out=np.array(A)
print(Out)
print(Out.dtype)


### Get number of employee from user for each user collect folowing information
- Id
- Salary
- Pin Code
- Dept. Id
# Store the information collected in 2 dimentional array and print Number of employee having salary greater than 30000 with their Id Number


In [ ]:
from numpy.core.multiarray import empty_like
Num=int(input("Enter Count Of Emps: "))
Empid=[]
EmpSal=[]
Emppin=[]
EmpDid=[]
for i in range(Num):
  Empid.append(int(input("Emp id of Emp No. "+str(i))))
  EmpSal.append(int(input("Salary of Emp No. "+str(i))))
  Emppin.append(int(input("Pin Number of Emp No. "+str(i))))
  EmpDid.append(int(input("Dept. id of Emp No. "+str(i))))
  
print(Empid)
print(EmpSal)
print(Emppin)
print(EmpDid)


In [ ]:
Info=np.array([Empid,EmpSal,Emppin,EmpDid])
print(Info.shape)
print(Info.ndim)
print(Info)

(4, 3)
2
[[    45      8    112]
 [ 10000  45454 465465]
 [112244 112123 122244]
 [     5      4    232]]


In [ ]:
Temp=Info[1,:] # salary row number 
cnt=0
for i in range(len(Temp)):
  if Temp[i]>30000:
    cnt+=1
    print(Info[0,i])
print("Total Count of Emp above 30k are ",cnt)    

8
112
Total Count of Emp above 30k are  2


In [ ]:
Temp=Info[1,:]
cnt=0
Inf=[]
for i in range(len(Temp)):
  if Temp[i]>30000:
    cnt+=1
    Inf.append(i)

print("Total Count of Emp above 30k are ",cnt) 
for i in Inf:
  print(Info[0,i])
  

Total Count of Emp above 30k are  2
8
112


In [ ]:
Temp=Info[1,:]
print(Temp[Temp>30000])
print(len(Temp[Temp>30000]))
print(Info[0,Temp>30000])



[ 45454 465465]
2
[  8 112]


In [ ]:
print(Info)
Temp=Info[0,:]
print(Info[2,Temp>10])

[[    45      8    112]
 [ 10000  45454 465465]
 [112244 112123 122244]
 [     5      4    232]]
[112244 122244]
