In [ ]:
import numpy as np

A=np.random.randint(5,100,(5,5))
print(A)
print(A[1:4,1:4])

In [ ]:
A=np.random.randn(5)
print(A)


In [ ]:
A=np.random.randint(5,100,(5,5))
print(A)
print(A.max())
print(A.max(axis=1))
print(A.max(axis=0))

In [ ]:
print(A)
print(A.sum())
print(A.sum(axis=1))
print(A.sum(axis=0))


In [ ]:
# Mathematical Operations in Array
A=np.random.randint(1,5,(2,2))
B=np.random.randint(1,5,(2,2))
print(A)
print(B)
#print(A+B)
#print(A-B)
#print(A*B)
print(A.dot(B))

In [ ]:
# Wap To generate 2 arrays of length 5x5
# The elements of first array must be float and in range of
# 5 to 50
# The second array have negative and positive elements
# As a output print the summation of both arrays
# print summation array in row wise sorted form

# Solution:
A1=np.random.randint(5,50,(5,5))*0.4
A2=np.random.randn(5,5)
print(A1)
print(A2)
A3=A1+A2
print(A3)
print(np.sort(A3,axis=1))
print(A3)

In [ ]:
print(A3)
A3.sort(axis=1)
print(A3)

In [ ]:
A1=np.random.randint(1,5,(3,3))
A2=np.random.randint(1,5,(3,3))
print(A1)
print(A2)
# Joining
A3=np.array(list(A1)+list(A2))
print(A3)

In [ ]:
print(A1)
print(A2)
A3=np.zeros((6,3))
A3[0:3,0:3]=A1
A3[3:6,0:3]=A2
print(A3)

A3=np.zeros((3,6))
A3[0:3,0:3]=A1
A3[0:3,3:6]=A2
print(A3)


In [ ]:
A3=np.concatenate((A1,A2),axis=1)
print(A3)
A3=np.concatenate((A1,A2),axis=0)
print(A3)

# WAP to collect data of 2 diferent companies
- Count of employees
Both the companies employess should enter following information
- Age
- Salary
- Incentives
- Years of experience

# Once both companies info is collected
Perform following Task
- Create an array having colective information of employee having salary greater than 10000, and print the array
-Update the Company 1 array with only entries having age <50





In [ ]:
# Company 1
Cnt1=int(input("No of EMp in Comp1: "))
CMP1Aray=np.zeros((Cnt1,4),dtype=int)
for i in range(Cnt1):
  tempo=list(map(int,input("Enter Details of Emp"+str(i+1)).split(",")))
  info=np.array(tempo)
  CMP1Aray[i,:]=info
print(CMP1Aray)

# Company 2
Cnt2=int(input("No of EMp in Comp2: "))
CMP2Aray=np.zeros((Cnt2,4),dtype=int)
for i in range(Cnt1):
  tempo=list(map(int,input("Enter Details of Emp"+str(i+1)).split(",")))
  info=np.array(tempo)
  CMP2Aray[i,:]=info
print(CMP2Aray)

No of EMp in Comp1: 3
Enter Details of Emp145,15000,1000,2
Enter Details of Emp212,13000,500,3
Enter Details of Emp319,8500,1000,2
[[   45 15000  1000     2]
 [   12 13000   500     3]
 [   19  8500  1000     2]]
No of EMp in Comp2: 3
Enter Details of Emp137,8500,500,1
Enter Details of Emp212,4500,500,3
Enter Details of Emp345,15000,2000,5
[[   37  8500   500     1]
 [   12  4500   500     3]
 [   45 15000  2000     5]]


In [ ]:
Myinfo=np.concatenate((CMP1Aray,CMP2Aray),axis=0)
print(Myinfo)
tmp=Myinfo[:,1]<10000
print(tmp)
print(Myinfo[tmp,:])

In [ ]:
for i in range(len(Myinfo)):
  tmp=Myinfo[i,1]
  if tmp<10000:
    print(Myinfo[i,:])

In [ ]:
# Update the Company 1 array with only entries having age <50
print(CMP1Aray)
CMP1Aray=CMP1Aray[CMP1Aray[:,0]<50,:]
print(CMP1Aray)

# Error Case
# CMP1Aray=CMP1Aray[(20<CMP1Aray[:,0]<50),:]
# print(CMP1Aray)


In [ ]:
A=np.array([2,4,5,7,8,5])
print(A)
A=np.delete(A,3)
print(A)

In [ ]:
A=np.append(A,45)
print(A)

In [ ]:
A=np.insert(A,2,45)
print(A)

In [ ]:
# Solution
A=np.array([1,2,3,4,5,6,7,8,9,10])
print(A)
print("Press 1 for Delete")
print("Press 2 for Append")
print("Press 3 for Insert")
print("Press 4 for Exit")
Opt=input("Enter Your Option: ")
if Opt=='1':
  ind=int(input("Enter index To delete: "))
  A=np.delete(A,ind)
  print(A)
elif Opt=='2':
  Val=int(input("Enter Value To Append: "))
  A=np.append(A,Val)
  print(A)
elif Opt=='3':
  ind=int(input("Enter index where to insert: "))
  Val=int(input("Enter value To insert: "))
  A=np.insert(A,ind,Val)
  print(A)
elif Opt=='4':
  print("Thanks For Using Our SoftwaRE")
else:
  print("Option Not Available")




In [ ]:
# for joining Arrays
# stack
# vstack
# hstack
# dstack
# Search (search, sortsearch)
# Splitting (array_split)

In [ ]:
# Boolean Indexing Questions
# create an array of length 5x5
# using boolean indexing 
# print all values greater than 50
# print all values of row one those are divsible by 5
# add and print all values of array those are even
