In [ ]:
import numpy as np
A=np.array([1,2,3,4],dtype=str)
print(A)
print(type(A))
print(A.dtype)

['1' '2' '3' '4']
<class 'numpy.ndarray'>
<U1


In [ ]:
# Numpy Functions
A=np.zeros((2,2))
print(A)

A1=np.random.rand(12) # count of element, 0-1
print(A1)

A2=np.random.random((3,3)) # size of array , 0-1
print(A2)


In [ ]:
A3=np.ones((2,2))
print(A3)

[[1. 1.]
 [1. 1.]]


# WAP having a function with input arguments as 
- Type
- No of rows 
- No of colmns
it will have the following cases to fulfil
- If type =1
  - It should generate a random array of given length
- if type =2 
  - it should generate a array of given length and ask a number from user 
  the output of type 2 will be as follow
  Ex. If size given is 2,3 ands no given by user is 5 than the output array must be 
   [5 5 5
    5 5 5]


In [ ]:
def MyFun(typ,rws,cols):
  if typ==1:
    Out=np.random.random((rws,cols))
  elif typ==2:
    num=int(input("Enter A number: "))
    Out=np.ones((rws,cols))*num
  return Out

In [ ]:
Out=MyFun(1,3,4)
print(Out)

In [ ]:
Out=MyFun(2,3,4)
print(Out)

In [ ]:
# Other Functions
A=np.full((3,4),45)
print(A)
# generating a sequence of given input
A=np.arange(5)  # end point from 0
print(A)
A=np.arange(5,15)  # start and end point
print(A)
A=np.arange(5,15,2) # start end and step 
print(A)

In [ ]:
A=np.linspace(11,20,11)
print(A)

[11.  11.9 12.8 13.7 14.6 15.5 16.4 17.3 18.2 19.1 20. ]


In [ ]:
A=np.linspace(11,20,11,endpoint=False)
print(A)

[11.         11.81818182 12.63636364 13.45454545 14.27272727 15.09090909
 15.90909091 16.72727273 17.54545455 18.36363636 19.18181818]


In [ ]:
# wap to generate a sequence of Desired length with in range
Strt=11
Stop=20
Reqpoint=50
Stpsiz=(Stop-Strt)/Reqpoint
for i in range(Reqpoint):
  Strt=Strt+Stpsiz
  print(Strt)

In [ ]:
A=np.eye(5)
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
A=np.diag([10,20,30,40,50])
print(A)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


In [ ]:
# Get input from user in terms of expenses of last 5 months
# Calculate mean, max, min, max-min, max-mean, mean-min
# Generate a 2 dimentional array having information as follow
# info=[Em1, Em2, Em3,Em4,Em5
#      mean, max, min, max-min, max-mean, mean-min]
# Hint:
# Em1=5
# Em2=8
# Em3=4
# Em4=8
# Em5=9
# info=[5,8,4,8,9
#      mean, max, min, max-min, max-mean, mean-min]

TmpEx=[]
for i in range(6):
  TmpEx.append(int(input("Enter Expense of Month "+str(i+1)+': ')))
print(TmpEx)

Inf=[np.mean(TmpEx),np.max(TmpEx),np.min(TmpEx),
     np.max(TmpEx)-np.min(TmpEx),np.max(TmpEx)-np.mean(TmpEx),
     np.mean(TmpEx)-np.min(TmpEx)]
print(Inf)

MyArray=np.array([TmpEx,Inf])
print(MyArray)

# print the expnses in diagonal form by using 
# slicing from above array info
# using diagonal array
# Hint:
# slice value of expense from info array
# and print using diagonal function of numpy

# syntax: A[rows,colmns]
print(np.diag(MyArray[0,:]))


# Generate an array showning values as from slicing it from INfo array
#[mean,mean,mean,mean,mean
# max,max,max,max,max
# min,min,min,min,min
# max-min,max-min,max-min,max-min,max-min
# max-mean,max-mean,max-mean,max-mean,max-mean
# mean-min, mean-min, mean-min, mean-min, mean-min]

# hint
# use loops or np.full, or np.ones to get output
Ary=np.ones((6,5))
Tmp=MyArray[1,:]
for i in range(6):  # rows
  for j in range(5):  # colmns
    Ary[i,j]*=Tmp[i]
print(Ary) 

In [ ]:
Ary=np.ones((6,5))
Tmp=MyArray[1,:]
for i in range(6):  # rows
    Ary[i,:]*=Tmp[i]
print(Ary) 

In [ ]:
Ary=np.ones((6,5))
Tmp=MyArray[1,:]
for i in range(6):  # rows
    Ary[i,:]=np.full((1,5),Tmp[i])
print(Ary) 


In [ ]:
# Numpy reshape
A=np.array([[4,5,7,8],[9,5,4,5]])
print(A)
B=np.reshape(A,(4,2))
print(B)

print(A.flatten())

[[4 5 7 8]
 [9 5 4 5]]
[[4 5]
 [7 8]
 [9 5]
 [4 5]]
[4 5 7 8 9 5 4 5]


In [ ]:
# generate a 2 d array of static length 
# random array values must be between 0-1
# from user get input as 
# do you want to change array shape or not
# if user enter 1
# get new rows and new cols
# check if new rows and new colmns are suitable for rehaping or not
# if suitable reshape the initial array and print
# else get new rows and new colmns again untill
# correct input not given

Row=4
Col=5
Initaray=np.random.random((Row,Col))
Opt=input("Enter Y for Change shape and N for Not Changing Shape: ")
if Opt=="Y":
  nrw=int(input("Enter New Rows: "))
  ncl=int(input("Enter New Colmns: "))




else:
  print(Initaray)








In [ ]:
a=np.random.random((5,5))
print(a)

[[0.54900304 0.69269685 0.88768617 0.40813735 0.91608688]
 [0.3998149  0.37847655 0.88299359 0.42128088 0.14736817]
 [0.55943384 0.07178193 0.57824126 0.15261713 0.29694756]
 [0.71508026 0.2156411  0.39326597 0.64380618 0.9149645 ]
 [0.63665365 0.47438209 0.81231797 0.62945015 0.62199528]]
